### ISSUE TITLE
Could we try CoDeNet on FPGA?

### ISSUE THREAD

**Issue by in-die-nibelungen** [DequanWang/CoDeNet#1]
Hi,
Thanks for your great work!!

Do you have a plan to put some files for FPGA inference of CoDeNet on this repo?

Thank you in advance.

**Comment by hqjenny** [comment]
Hello, thanks for your interest! 

We have uploaded our FPGA accelerator code at [https://github.com/hqjenny/CoDeNet](https://github.com/hqjenny/CoDeNet).
It is implemented in HLS and targets the Ultra96 FPGA flatform.

Please let us know if you have any other questions.

**Comment by in-die-nibelungen** [comment]
Hi, @hqjenny 

```
We have uploaded our FPGA accelerator code at https://github.com/hqjenny/CoDeNet.
It is implemented in HLS and targets the Ultra96 FPGA flatform.
```

Thank you for letting me know the repo!
I'll try it.
